# -*- coding: utf-8 -*-
# msg_en.py

msg_dict = {
    'add': 'add',
    'April': 'April',
    'August': 'August',
    'cannot delete category %(category_name)r with %(nr_of_expenses)s expenses assigned': 'cannot delete category %(category_name)r with %(nr_of_expenses)s expenses assigned',
    'Categories': 'Categories',
    'Category': 'Category',
    'category already exists %(existing)r, %(duplicate)r': 'category already exists %(existing)r, %(duplicate)r',
    'category_id must be integer not %r': 'category_id must be integer not %r',
    'check for updates': 'check for updates',
    'Color': 'Color',
    'Date': 'Date',
    'dayNamesMin_Fr': 'Fr',
    'dayNamesMin_Mo': 'Mo',
    'dayNamesMin_Sa': 'Sa',
    'dayNamesMin_Su': 'Su',
    'dayNamesMin_Th': 'Th',
    'dayNamesMin_Tu': 'Tu',
    'dayNamesMin_We': 'We',
    'December': 'December',
    'delete': 'delete',
    'edit': 'edit',
    'Expenses': 'Expenses',
    'Expenses Book': 'Expenses Book',
    'February': 'February',
    'Filter': 'Filter',
    'Friday': 'Friday',
    'hide details': 'hide details',
    'January': 'January',
    'July': 'July',
    'June': 'June',
    'March': 'March',
    'May': 'May',
    'Monday': 'Monday',
    'Name': 'Name',
    'name must not be empty': 'name must not be empty',
    'new category': 'new category',
    'Next': 'Next',
    'Note': 'Note',
    'November': 'November',
    'October': 'October',
    'Previous': 'Previous',
    'reset': 'reset',
    'Saturday': 'Saturday',
    'September': 'September',
    'show details': 'show details',
    'Sorting': 'Sorting',
    'submit': 'submit',
    'Summary': 'Summary',
    'Sunday': 'Sunday',
    'Thursday': 'Thursday',
    'Tuesday': 'Tuesday',
    'Update': 'Update',
    'Updates': 'Updates',
    'Value': 'Value',
    'Wednesday': 'Wednesday',
}
