# -*- coding: utf-8 -*-
# msg_de.py

msg_dict = {
    "add": "hinzufügen",
    "April": "April",
    "August": "August",
    "cannot delete category %(category_name)r with %(nr_of_expenses)s expenses assigned": "kann Kategorie %(category_name)r mit %(nr_of_expenses)s verknüpften Ausgaben nicht löschen",
    "Categories": "Kategorien",
    "Category": "Kategorie",
    "category already exists %(existing)r, %(duplicate)r": "Kategorie %(existing)r existiert bereits: %(duplicate)r",
    "category_id must be integer not %r": "category_id muss integer sein, nicht %r",
    "check for updates": "auf Updates prüfen",
    "Color": "Farbe",
    "Date": "Datum",
    "dayNamesMin_Fr": "Fr",
    "dayNamesMin_Mo": "Mo",
    "dayNamesMin_Sa": "Sa",
    "dayNamesMin_Su": "So",
    "dayNamesMin_Th": "Do",
    "dayNamesMin_Tu": "Di",
    "dayNamesMin_We": "Mi",
    "December": "Dezember",
    "delete": "löschen",
    "edit": "bearbeiten",
    "Expenses": "Ausgaben",
    "Expenses Book": "Haushaltsbuch",
    "February": "Februar",
    "Filter": "Filter",
    "Friday": "Freitag",
    "hide details": "Details ausblenden",
    "January": "Januar",
    "July": "Juli",
    "June": "Juni",
    "March": "März",
    "May": "Mai",
    "Monday": "Montag",
    "Name": "Name",
    "name must not be empty": "Name darf nicht leer sein",
    "new category": "neue Kategorie",
    "Next": "Weiter",
    "Note": "Notiz",
    "November": "November",
    "October": "Oktober",
    "Previous": "Zurück",
    "reset": "zurücksetzen",
    "Saturday": "Samstag",
    "September": "September",
    "show details": "Details einblenden",
    "Sorting": "Sortierung",
    "submit": "übertragen",
    "Summary": "Übersicht",
    "Sunday": "Sonntag",
    "Thursday": "Donnerstag",
    "Tuesday": "Dienstag",
    "Update": "Aktualisieren",
    "Updates": "Aktualisierungen",
    "Value": "Wert",
    "Wednesday": "Mittwoch",
}
